#!/usr/bin/env python3
"""Code Generator v4.0 — SynChanCyberSecurity"""
import os, re
from datetime import datetime

class CodeGenerator:
    def __init__(self, projects_dir="~/neural-chan/projects"):
        self.projects_dir = os.path.expanduser(projects_dir)
        os.makedirs(self.projects_dir, exist_ok=True)

    def detect_language(self, t):
        lang_map = {
            "python": ["python","py ",".py","django","flask","fastapi","script"],
            "bash": ["bash","shell","sh ",".sh","zsh"],
            "go": ["golang","go ",".go"],
            "rust": ["rust","cargo",".rs"],
            "javascript": ["javascript","js ","node","nodejs"],
            "typescript": ["typescript","ts ","angular","vue"],
            "sql": ["sql","mysql","postgresql","sqlite"],
            "docker": ["docker","dockerfile","container"],
            "html": ["html","css","frontend","web page"],
        }
        t_lower = t.lower()
        for lang, kws in lang_map.items():
            for kw in kws:
                if kw in t_lower:
                    return lang
        return "python"

    def generate(self, raw, lang, complexity):
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        pname = re.sub(r"[^a-z0-9]+", "_", raw[:40].lower()).strip("_")[:30]
        pdir = os.path.join(self.projects_dir, f"{pname}_{ts}")
        os.makedirs(pdir, exist_ok=True)

        if lang == "python":
            files = self._gen_python(raw, complexity)
        elif lang == "bash":
            files = self._gen_bash(raw, complexity)
        elif lang == "go":
            files = self._gen_go(raw, complexity)
        elif lang == "rust":
            files = self._gen_rust(raw, complexity)
        elif lang == "javascript":
            files = self._gen_js(raw, complexity)
        elif lang == "sql":
            files = self._gen_sql(raw, complexity)
        elif lang == "docker":
            files = self._gen_docker(raw, complexity)
        elif lang == "html":
            files = self._gen_html(raw, complexity)
        else:
            files = [{"filename":"main.txt","content":"# "+raw[:50]+"\n# TODO: implement"}]

        out = []
        for f in files:
            path = os.path.join(pdir, f["filename"])
            with open(path, "w") as fh:
                fh.write(f["content"])
            out.append({"path":path,"filename":f["filename"],"size":len(f["content"]),"content":f["content"]})
        return out

    def _gen_python(self, raw, complexity):
        files = []
        main = """#!/usr/bin/env python3
# """ + raw[:60] + """
# Generated by Neural Chan v4.0 — SynChanCyberSecurity

import sys, os, json, threading, argparse, socket
from queue import Queue

def is_open(host, port, timeout=1):
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.settimeout(timeout)
        r = s.connect_ex((host, port))
        s.close()
        return r == 0
    except:
        return False

def worker(q, func, out):
    while not q.empty():
        try:
            item = q.get_nowait()
            r = func(item)
            if r: out.append(r)
            q.task_done()
        except: break

def threaded(items, func, threads=10):
    q = Queue()
    for i in items: q.put(i)
    results = []
    for _ in range(min(threads, len(items))):
        t = threading.Thread(target=worker, args=(q, func, results))
        t.daemon = True
        t.start()
    q.join()
    return results

def main():
    p = argparse.ArgumentParser(description=""" + repr(raw[:40]) + """)
    p.add_argument("--target","-t", required=True)
    p.add_argument("--ports","-p", default="1-1000")
    p.add_argument("--threads","-T", type=int, default=50)
    p.add_argument("--timeout", type=float, default=1.0)
    p.add_argument("--output","-o", default="results.json")
    args = p.parse_args()

    print(f"[*] Scanning {args.target} ports {args.ports}")
    if "-" in args.ports:
        a,b = map(int, args.ports.split("-"))
        ports = range(a, b+1)
    else:
        ports = [int(x) for x in args.ports.split(",")]

    open_ports = threaded(
        [(args.target, p, args.timeout) for p in ports],
        lambda x: {"port":x[1],"open":True} if is_open(x[0],x[1],x[2]) else None,
        args.threads
    )
    open_ports = [p for p in open_ports if p]

    with open(args.output,"w") as f:
        json.dump(open_ports, f, indent=2)

    print(f"[*] Done. {len(open_ports)} open ports. Saved to {args.output}")

if __name__ == "__main__":
    main()
"""
        files.append({"filename":"main.py","content":main})
        if complexity == "complex":
            utils = """# Utility module
import socket, requests

def grab_banner(host, port, timeout=2):
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.settimeout(timeout)
        s.connect((host, port))
        b = s.recv(1024).decode("utf-8", errors="ignore").strip()
        s.close()
        return b
    except:
        return None
"""
            files.append({"filename":"utils.py","content":utils})
            files.append({"filename":"requirements.txt","content":"requests>=2.28.0\ncolorama>=0.4.5\n"})
            files.append({"filename":"README.md","content":"# "+raw[:30]+"\n\nGenerated by Neural Chan v4.0\n\n## Usage\n```bash\npython3 main.py --target 192.168.1.1 --ports 1-65535 --threads 100\n```\n"})
        return files

    def _gen_bash(self, raw, complexity):
        script = """#!/bin/bash
# """ + raw[:50] + """
# Generated by Neural Chan v4.0 — SynChanCyberSecurity
set -euo pipefail
TARGET="${1:-}"
OUTPUT="${2:-./output}"
THREADS="${THREADS:-10}"
[[ -z "$TARGET" ]] && { echo "[!] Usage: $0 <target> [output]"; exit 1; }
mkdir -p "$OUTPUT"
echo "[*] Starting on $TARGET"
echo "[*] Done. Results in $OUTPUT"
"""
        files = [{"filename":"run.sh","content":script}]
        if complexity == "complex":
            lib = """#!/bin/bash
log_info()  { echo -e "\033[32m[+]\033[0m $1"; }
log_warn()  { echo -e "\033[33m[!]\033[0m $1"; }
log_error() { echo -e "\033[31m[-]\033[0m $1"; }
"""
            files.append({"filename":"lib.sh","content":lib})
        return files

    def _gen_go(self, raw, complexity):
        return [{"filename":"main.go","content":"package main\n\n// "+raw[:50]+"\nfunc main() {\n    // TODO\n}"}]

    def _gen_rust(self, raw, complexity):
        return [{"filename":"main.rs","content":"fn main() {\n    // "+raw[:50]+"\n    println!(\"Ready\");\n}"}]

    def _gen_js(self, raw, complexity):
        return [{"filename":"index.js","content":"// "+raw[:50]+"\nconsole.log('Ready');"}]

    def _gen_sql(self, raw, complexity):
        return [{"filename":"schema.sql","content":"-- "+raw[:50]+"\n-- TODO: schema"}]

    def _gen_docker(self, raw, complexity):
        return [{"filename":"Dockerfile","content":"# "+raw[:50]+"\nFROM ubuntu:22.04\nCMD [\"echo\", \"Ready\"]"}]

    def _gen_html(self, raw, complexity):
        return [{"filename":"index.html","content":"<!DOCTYPE html><html><head><title>"+raw[:30]+"</title></head><body><h1>Ready</h1></body></html>"}]
