"""Memory Exporter — saves Neural Chan's brain as Markdown files."""
import os, json, glob
from datetime import datetime

class MemoryExporter:
    def __init__(self, data_dir='~/neural-chan/data', output_dir='~/neural-chan/memory'):
        self.data_dir = os.path.expanduser(data_dir)
        self.output_dir = os.path.expanduser(output_dir)
        os.makedirs(self.output_dir, exist_ok=True)
    
    def export_all(self):
        files = []
        files.append(self._export_vocabulary())
        files.append(self._export_history())
        files.append(self._export_system_metrics())
        files.append(self._export_web_knowledge())
        files.append(self._export_master_index())
        return [f for f in files if f]
    
    def _load_json(self, filename):
        path = os.path.join(self.data_dir, filename)
        try:
            with open(path, 'r') as f:
                return json.load(f)
        except:
            return None
    
    def _export_vocabulary(self):
        data = self._load_json('vocabulary_v2.json') or self._load_json('vocabulary.json') or {}
        if not data:
            return None
        
        md = f"""# Neural Chan — Vocabulary & Brain State

**Exported:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  
**Conversations:** {data.get('conversations', 0)}  
**Speech Proficiency:** {round(data.get('proficiency', 0), 1)}%  
**Words Learned:** {len(data.get('words', []))}  
**User Name:** {data.get('name', 'Unknown')}

---

## Personality Traits

| Trait | Score |
|-------|-------|
| Friendly | {data.get('personality', {}).get('friendly', 0.5)} |
| Analytical | {data.get('personality', {}).get('analytical', 0.5)} |

---

## Learned Vocabulary

"""
        words = data.get('words', [])
        if words:
            for i, word in enumerate(words, 1):
                md += f"{i}. `{word}`\n"
        else:
            md += "*No words learned yet.*\n"
        
        md += f"""

---

*Auto-generated by Neural Chan Memory Exporter*
"""
        path = os.path.join(self.output_dir, 'vocabulary.md')
        with open(path, 'w') as f:
            f.write(md)
        return path
    
    def _export_history(self):
        data = self._load_json('history_v2.json') or self._load_json('conversation_history.json') or []
        if not data:
            return None
        
        md = f"""# Neural Chan — Conversation History

**Exported:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  
**Total Exchanges:** {len(data)}

---

"""
        for i, entry in enumerate(data[-50:], 1):
            ts = entry.get('time', '?')
            user = entry.get('user', '?')
            bot = entry.get('bot', '?')
            intent = entry.get('intent', '?')
            md += f"""### Exchange {i}
- **Time:** `{ts}`
- **Intent:** `{intent}`
- **User:** {user}
- **Neural Chan:** {bot}

---
"""
        path = os.path.join(self.output_dir, 'conversation_history.md')
        with open(path, 'w') as f:
            f.write(md)
        return path
    
    def _export_system_metrics(self):
        data = self._load_json('system_metrics.json') or []
        if not data:
            return None
        
        latest = data[-1] if data else {}
        md = f"""# Neural Chan — System Monitor Logs

**Exported:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  
**Total Samples:** {len(data)}

---

## Latest Reading

| Metric | Value |
|--------|-------|
| CPU | {latest.get('cpu_percent', 'N/A')}% |
| Memory | {latest.get('mem_percent', 'N/A')}% |
| Disk | {latest.get('disk_percent', 'N/A')}% |
| Processes | {latest.get('processes', 'N/A')} |
| Load (1m) | {latest.get('load_1m', 'N/A')} |
| Load (5m) | {latest.get('load_5m', 'N/A')} |
| Load (15m) | {latest.get('load_15m', 'N/A')} |

---

## Top Processes (Latest)

"""
        procs = latest.get('top_processes', [])
        if procs:
            md += "| PID | Name | CPU% |\n|-----|------|------|\n"
            for p in procs:
                md += f"| {p.get('pid', '?')} | {p.get('name', '?')} | {p.get('cpu', '?')}% |\n"
        else:
            md += "*No process data available.*\n"
        
        md += f"""

---

## Historical Summary

- **First Sample:** {data[0].get('time', '?') if data else '?'}
- **Last Sample:** {data[-1].get('time', '?') if data else '?'}

*Auto-generated by Neural Chan Memory Exporter*
"""
        path = os.path.join(self.output_dir, 'system_metrics.md')
        with open(path, 'w') as f:
            f.write(md)
        return path
    
    def _export_web_knowledge(self):
        data = self._load_json('web_knowledge.json') or {}
        if not data:
            return None
        
        md = f"""# Neural Chan — Web Knowledge Base

**Exported:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  
**Cached Topics:** {len(data)}

---

"""
        for topic, entry in sorted(data.items()):
            cached = entry.get('cached', '?')
            query = entry.get('query', topic)
            summary = entry.get('summary', 'No summary.')
            md += f"""## {query}

- **Cached:** `{cached}`
- **Summary:** {summary}

---
"""
        path = os.path.join(self.output_dir, 'web_knowledge.md')
        with open(path, 'w') as f:
            f.write(md)
        return path
    
    def _export_master_index(self):
        md = f"""# Neural Chan — Memory Index

**Exported:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  
**Memory Directory:** `~/neural-chan/memory/`

---

## Available Memory Files

| File | Description |
|------|-------------|
| [vocabulary.md](vocabulary.md) | Learned words, proficiency, personality traits |
| [conversation_history.md](conversation_history.md) | Last 50 user exchanges |
| [system_metrics.md](system_metrics.md) | Live CPU/memory/process logs |
| [web_knowledge.md](web_knowledge.md) | DuckDuckGo search cache |

---

## Quick Stats

- All memory persists across reboots
- Auto-saved every 30 seconds during runtime
- Markdown format for human readability + git tracking

---

*Neural Chan OS v2.3 — SynChanCyberSecurity*
"""
        path = os.path.join(self.output_dir, 'README.md')
        with open(path, 'w') as f:
            f.write(md)
        return path
