#!/usr/bin/env python3
# call me sin
# Generated by Neural Chan v4.0 — SynChanCyberSecurity

import sys, os, json, threading, argparse, socket
from queue import Queue

def is_open(host, port, timeout=1):
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.settimeout(timeout)
        r = s.connect_ex((host, port))
        s.close()
        return r == 0
    except:
        return False

def worker(q, func, out):
    while not q.empty():
        try:
            item = q.get_nowait()
            r = func(item)
            if r: out.append(r)
            q.task_done()
        except: break

def threaded(items, func, threads=10):
    q = Queue()
    for i in items: q.put(i)
    results = []
    for _ in range(min(threads, len(items))):
        t = threading.Thread(target=worker, args=(q, func, results))
        t.daemon = True
        t.start()
    q.join()
    return results

def main():
    p = argparse.ArgumentParser(description='call me sin')
    p.add_argument("--target","-t", required=True)
    p.add_argument("--ports","-p", default="1-1000")
    p.add_argument("--threads","-T", type=int, default=50)
    p.add_argument("--timeout", type=float, default=1.0)
    p.add_argument("--output","-o", default="results.json")
    args = p.parse_args()

    print(f"[*] Scanning {args.target} ports {args.ports}")
    if "-" in args.ports:
        a,b = map(int, args.ports.split("-"))
        ports = range(a, b+1)
    else:
        ports = [int(x) for x in args.ports.split(",")]

    open_ports = threaded(
        [(args.target, p, args.timeout) for p in ports],
        lambda x: {"port":x[1],"open":True} if is_open(x[0],x[1],x[2]) else None,
        args.threads
    )
    open_ports = [p for p in open_ports if p]

    with open(args.output,"w") as f:
        json.dump(open_ports, f, indent=2)

    print(f"[*] Done. {len(open_ports)} open ports. Saved to {args.output}")

if __name__ == "__main__":
    main()
